[project]
name = "encrypt-bridge"
authors = ["Anonymous Developer"]
description = "A secure, cross-chain token synchronization and encryption bridge"
telemetry = false
requirements = []

[contracts.access-control]
path = "contracts/access-control.clar"
depends_on = []

[contracts.event-log]
path = "contracts/event-log.clar"
depends_on = []

[contracts.token-encryptor]
path = "contracts/token-encryptor.clar"
depends_on = []

[contracts.token-vault]
path = "contracts/token-vault.clar"
depends_on = []

[contracts.sync-manager]
path = "contracts/sync-manager.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
